sudo: false

notifications:
  email:
    recipients:
      gtarcea@umich.edu
      weymouth@umich.ed

language: python

python:
  - 2.7

env:
  global:
    - MCDIR=/tmp/mcdir
    - MCDB_TYPE=rethinkdb
    - MCDB_NAME=materialscommons
    - MCDB_FILE=rethink_startup/rethinkdb_dump_test_data.tar.gz
    - MCDB_PORT=30815
    - MCDB_CONNECTION=localhost:$MCDB_PORT
    - RETHINKDB_CLUSTER_PORT=31815
    - RETHINKDB_HTTP_PORT=8090

before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rethinkdb
  - 'nvm install v5.3.0'
  - sudo pip install rethinkdb
  - sudo pip install Flask
  - sudo pip install pytest
  - node --version
  - pip list

install:
  - pwd
  - pushd ~
  - git clone -b sprint https://github.com/materials-commons/materialscommons.org.git
  - pushd materialscommons.org
  - npm install
  - pushd backend
  - bash mcservers start
  - bash mcservers
  - popd
  - popd
  - popd
  - pwd
  - cd python
  - pip install -r requirements.txt
  - python setup.py install --user

script:
  - pytest test

